name: reusable_workflow
<<<<<<< HEAD
on:
  workflow_call
    outputs:
      new_var: 
        value: ${{ jobs.called_job.outputs.test}}
=======
on: 
  workflow_call
    outputs:
      new_var: 
        value: ${{ jobs.called_job.outputs.test}}
>>>>>>> origin/master
jobs:
  called_job:
    runs-on: ubuntu-Latest
    outputs:
      test: ${{ steps.new_var.outputs.testvar}}
    steps:
    - name: echo output
      id: new_var
      run: echo testvar=hello >> $GITHUB_OUTPUT
